# Generated by Django 5.2 on 2025-04-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapprest", "0003_booking"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignedAgreementUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15)),
                ("file", models.FileField(upload_to="signed_agreements/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
