# Generated by Django 5.2 on 2025-04-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapprest", "0005_uploadedagreement"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedagreement",
            name="sender_phone",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
