# Generated by Django 5.2 on 2025-05-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapprest", "0006_uploadedagreement_sender_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("capacity", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "location",
                    models.CharField(default="Ardhi University", max_length=255),
                ),
                ("available_date", models.DateField()),
                ("image", models.ImageField(upload_to="room_images/")),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
    ]
